# -*- coding: utf-8 -*-
"""4ik25cs236_exp_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tUdqYjkEhZwGDVVQV_n8C4SdOuNnbfeq
"""

import numpy as np
import pandas as pd

marks=np.array([80,85,90,95,100])
print(marks)
print(marks.mean())
print(marks.shape)
df = pd.DataFrame({
    "name": ["Aditya Kapoor", "Neha Malhotra", "Rahul Bansal", "Meera Joshi", "Arjun Patel",
"Kavya Reddy", "Nitin Agarwal", "Diya Choudhary", "Siddharth Jain", "Ritika Sen"],
    "marks": [85, np.nan, 76, 88, 67, 95, 81, 73, 90, 78],
    "branch": [
        "Computer Science", "Electronics", "Mechanical", np.nan, "Civil",
        "Computer Science", np.nan, "Mechanical", "Information Technology", "Civil"
    ]
})
print(df)
print(df.describe())
print(df.marks.mean())
print(df.iloc[0:2])
print(df.duplicated())
print(df.isnull().sum())