# -*- coding: utf-8 -*-
"""4ik25cs236_exp_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GDkZ89Cv5g2uDxYKvoFngmx-UUdWOZEE
"""

import numpy as np
import pandas as pd

data = {
"Name": ["Aarav", "Ishita", "Dev", "Sanya", "Ritik","Neha", "Yash", "Anvi", "Harsh", "Tanya","Vivek", "Siddhi", "Omkar", "Bhavna", "Ritesh","Aditi", "Kush", "Lavanya", "Aryan", "Pallavi","Varun", "Krishna", "Mitali", "Gaurav", "Shruti"],
"Marks": [88, np.nan, 76, 91, 83,95, 72, np.nan, 87, 79,68, 90, np.nan, 85, 92,74, 81, 96, np.nan, 89,77, 84, 93, np.nan, 86],
"Age": [21, 20, np.nan, 22, 19,21, 20, 23, np.nan, 22,19, 21, 20, np.nan, 23,22, 19, 20, 21, np.nan,22, 20, 21, 23, np.nan],
"City": ["Bengaluru", "Mysuru", "Hubballi", "Mangaluru", "Belagavi","Tumakuru", "Shivamogga", "Dharwad", "Kalaburagi", "Udupi","Bidar", "Hassan", "Raichur", "Ballari", "Vijayapura","Kolar", "Chikkaballapur", "Mandya", "Davanagere", "Hosapete","Chitradurga", "Bagalkote", "Karwar", "Gadag", "Bengaluru"]
}
df = pd.DataFrame(data)
print(df)
print(df.shape)
print(df.columns.tolist())
print(df.dtypes)
df.info()
print(df.describe())
print(df.mean(numeric_only=True))
print(df.median(numeric_only=True))
print(df.mode(numeric_only=True))
print(df.std(numeric_only=True))
print(df.isnull())
print(df.isnull().sum())
print(df.isnull().sum().sum())
print(df[df.duplicated()])
print(df.duplicated().sum())